import os
q_scores = str(config['qscores']).split(',')
lengths = str(config['lengths']).split(',')
aug_config = os.path.join(str(config['wrapper_dir']), 'resources/augustus_config')
busco_downloads = os.path.join(str(config['wrapper_dir']), 'resources/busco_downloads')
samples = [file.split('.')[0] for file in os.listdir('data') if file.endswith('fastq.gz')]

if workflow.cores > 48:
    braker_threads = 48
else:
    braker_threads = workflow.cores

if workflow.cores > 20:
    nextdenovo_threads = 20
else:
    nextdenovo_threads = workflow.cores

rule all:
    input:
        expand('results/final/{sample}/eukaryotes.fasta', sample=samples),
        
rule clean_fastq:
    input:
        'data/{sample}.fastq.gz'
    output:
        'results/clean_fastq/{sample}.fastq.gz'
    log:
        'results/logs/clean_fastq/{sample}.log'
    params:
        contam='resources/contaminants.fasta'
    threads:
        workflow.cores
    conda:
        'envs/clean_fastq.yaml'
    shell:
        'minimap2 -t {threads} -ax map-ont {params.contam} {input} 2> {log} | samtools fastq -n -f 4 - 2>> {log} | gzip > {output} 2>> {log}'

rule chopper:
    input:
        'results/clean_fastq/{sample}.fastq.gz'
    output:
        'results/chopper/{sample}.fastq.gz'
    log:
        'results/logs/chopper/{sample}.log'
    params:
        length = 1000,
        quality = 10
    threads:
        workflow.cores
    conda:
        'envs/chopper.yaml'
    shell:
        'gunzip -c {input} 2> {log} | chopper -l {params.length} -q {params.quality} --threads {threads} 2>> {log} | gzip > {output} 2>> {log}'

rule metaflye:
    input:
        'results/chopper/{sample}.fastq.gz'
    output:
        'results/metaflye/{sample}/assembly.fasta',
        'results/metaflye/{sample}/assembly_graph.gfa',
        'results/metaflye/{sample}/assembly_graph.gv',
        'results/metaflye/{sample}/assembly_info.txt',
    log:
        'results/logs/metaflye/{sample}.log'
    params:
        out_dir='results/metaflye/{sample}'
    threads:
        workflow.cores
    conda:
        'envs/flye.yaml'
    shell:
        '''
        flye \
            --meta \
            --no-alt-contigs \
            --nano-raw {input} \
            --out-dir {params.out_dir} \
            --threads {threads} &> {log}
        '''

rule whokaryote:
    input:
        'results/metaflye/{sample}/assembly.fasta'
    output:
        'results/whokaryote/{sample}/eukaryotes.fasta',
        'results/whokaryote/{sample}/prokaryotes.fasta',
        'results/whokaryote/{sample}/whokaryote_predictions_T.tsv',
    log:
        'results/logs/whokaryote/{sample}.log'
    threads:
        workflow.cores
    params:
        out_dir='results/whokaryote/{sample}',
    conda:
        'envs/whokaryote.yaml'
    shell:
        '''
        whokaryote.py --contigs {input} --outdir {params.out_dir} --threads {threads} --f &> {log}
        '''

rule bakta:
    input:
        'results/whokaryote/{sample}/prokaryotes.fasta'
    output:
        'results/bakta/{sample}/prokaryotes.gff3'
    log:
        'results/logs/bakta/{sample}.log'
    params:
        out_dir='results/bakta/{sample}',
        db=os.path.join(str(config['wrapper_dir']), 'resources/db-light'),
    conda:
        'envs/bakta.yaml'
    shell:
        'bakta --keep-contig-headers --db {params.db} --force --output {params.out_dir} {input} &> {log}'

rule gc_content:
    input:
        'results/whokaryote/{sample}/whokaryote_predictions_T.tsv',
        'results/metaflye/{sample}/assembly.fasta'
    output:
    log:
        'results/logs/gc_content/{sample}.log'
    script:
        'scripts/post_who_gc_content.py'

rule cleaner_fastq:
    input:
        'results/whokaryote/{sample}/prokaryotes.fasta',
        'results/clean_fastq/{sample}.fastq.gz'
    output:
        'results/cleaner_fastq/{sample}.fastq.gz'
    log:
        'results/logs/cleaner_fastq/{sample}.log'
    threads:
        workflow.cores
    conda:
        'envs/clean_fastq.yaml'
    shell:
        '''
        minimap2 -t {threads} -ax map-ont {input[0]} {input[1]} 2> {log} | \
        samtools fastq -n -f 4 - | gzip > {output} 2>> {log}
        '''

rule nextdenvovo:
    input:
        'results/cleaner_fastq/{sample}.fastq.gz',
        'results/whokaryote/{sample}/eukaryotes.fasta',
    output:
        'results/nextdenovo/{sample}/03.ctg_graph/nd.asm.fasta',
    log:
        'results/logs/nextdenovo/{sample}.log'
    params:
        out_dir='results/nextdenovo/{sample}',
    threads:
        nextdenovo_threads
    conda:
        'envs/nextdenovo.yaml'
    shell:
        '''
        ls {input[0]} > input.fofn
        echo "[General]" > run.cfg
        echo "job_type = local" >> run.cfg
        echo "job_prefix = nextDenovo" >> run.cfg
        echo "task = all" >> run.cfg
        echo "rewrite = yes" >> run.cfg
        echo "deltmp = yes" >> run.cfg
        echo "parallel_jobs = {threads}" >> run.cfg
        echo "input_type = raw" >> run.cfg
        echo "read_type = ont" >> run.cfg
        echo "input_fofn = input.fofn" >> run.cfg
        echo "workdir = {params.out_dir}" >> run.cfg
        echo "" >> run.cfg
        echo "[correct_option]" >> run.cfg
        echo "read_cutoff = 1k" >> run.cfg
        echo -n "genome_size = " >> run.cfg
        grep -o -E '[ATCG]' {input[1]} | wc -l >> run.cfg
        echo "sort_options = -m 20g -t 15" >> run.cfg
        echo "minimap2_options_raw = -t 8" >> run.cfg
        echo "pa_correction = 3" >> run.cfg
        echo "correction_options = -p 15" >> run.cfg
        echo "" >> run.cfg
        echo "[assemble_option]" >> run.cfg
        echo "minimap2_options_cns = -t 8" >> run.cfg
        echo "nextgraph_options = -a 1" >> run.cfg
        nextDenovo run.cfg &> {log}
        '''
        

rule nextdenovo_whokaryote:
    input:
        'results/nextdenovo/{sample}/03.ctg_graph/nd.asm.fasta'
    output:
        'results/nextdenovo_whokaryote/{sample}/eukaryotes.fasta',
        'results/nextdenovo_whokaryote/{sample}/whokaryote_predictions_T.tsv',
    log:
        'results/logs/nextdenovo_whokaryote/{sample}.log'
    threads:
        workflow.cores
    params:
        out_dir='results/nextdenovo_whokaryote/{sample}',
    conda:
        'envs/whokaryote.yaml'
    shell:
        'whokaryote.py --contigs {input} --outdir {params.out_dir} --threads {threads} --f &> {log}'

rule ragtag_scaffold:
    input:
        'results/nextdenovo_whokaryote/{sample}/eukaryotes.fasta',
        'results/whokaryote/{sample}/eukaryotes.fasta',
    output:
        'results/ragtag/{sample}/ragtag.scaffold.fasta',
    log:
        'results/logs/ragtag/{sample}.log'
    threads:
        workflow.cores
    params:
        out_dir='results/ragtag/{sample}'
    conda:
        'envs/ragtag.yaml'
    shell:
        '''
        ragtag.py scaffold \
            -o {params.out_dir} \
            {input[0]} {input[1]} &> {log}
        '''

rule quickmerge:
    input:
        'results/nextdenovo_whokaryote/{sample}/eukaryotes.fasta',
        'results/ragtag/{sample}/ragtag.scaffold.fasta',
        'results/bandage/{sample}/N50.txt'
    output:
        'results/quickmerge/{sample}/merged_metaflye_nextdenovo.fasta',
    log:
        'results/logs/quickmerge/{sample}.log'
    params:
        out_dir='results/quickmerge/{sample}'
    threads:
        workflow.cores
    conda:
        'envs/quickmerge.yaml'
    shell:
        """
        N50=$(cat {input[2]})
        merge_wrapper.py \
            {input[1]} {input[0]} -l $N50 \
            -pre metaflye_nextdenovo &> {log}
            python workflow/scripts/change_fasta_name.py merged_metaflye_nextdenovo.fasta {params.out_dir}/merged_metaflye_nextdenovo.fasta &> {log}
        """

rule medaka:
    input:
        'results/quickmerge/{sample}/merged_metaflye_nextdenovo.fasta',
        'results/cleaner_fastq/{sample}.fastq.gz'
    output:
        'results/medaka/{sample}/consensus.fastq'
    log:
        'results/logs/medaka/{sample}.log'
    params:
        out_dir='results/medaka/{sample}'
    threads:
        workflow.cores
    conda:
        'envs/medaka.yaml'
    shell:
        '''
        mini_align -r {input[0]} -i {input[1]} -t {threads} -p {params.out_dir}/mini_align &> {log}
        medaka_consensus \
            -i {params.out_dir}/mini_align.bam \
            -d {input[0]} \
            -o {params.out_dir} \
            -q \
            -t {threads} &>> {log}
        '''

rule medaka_chopper:
    input:
        'results/medaka/{sample}/consensus.fastq'
    output:
        'results/medaka/{sample}/consensus.fasta',
        'results/medaka/{sample}/consensus_q10.fastq'
    log:
        'results/logs/chopper/{sample}_q10fasta.log'
    params:
        quality = 10
    threads:
        workflow.cores
    conda:
        'envs/chopper.yaml'
    shell:
        """
        chopper -q {params.quality} -i {input} > {output[1]} 2>> {log}
        sed -n '1~4s/^@/>/p;2~4p' {output[1]} > {output[0]} 2>> {log}
        """

rule nanoplot:
    input:
        'results/medaka/{sample}/consensus_q10.fastq',
        'results/clean_fastq/{sample}.fastq.gz',
        'results/cleaner_fastq/{sample}.fastq.gz'
    output:
        'results/nanoplot/{sample}/final_NanoPlot-report.html',
        'results/nanoplot/{sample}/cleaned_NanoPlot-report.html',
        'results/nanoplot/{sample}/eukaryotic_NanoPlot-report.html'
    log:
        'results/logs/nanoplot/{sample}.log'
    params:
        out_dir='results/nanoplot/{sample}'
    threads:
        workflow.cores
    conda:
        'envs/nanoplot.yaml'
    shell:
        """
        NanoPlot -t {threads} -o {params.out_dir} --only-report -p final_ --fastq {input[0]} 2>> {log}
        NanoPlot -t {threads} -o {params.out_dir} --only-report -p cleaned_ --fastq {input[1]} 2>> {log}
        NanoPlot -t {threads} -o {params.out_dir} --only-report -p eukaryotic_ --fastq {input[2]} 2>> {log}
        """

rule repeatmodeler:
    input:
        'results/medaka/{sample}/consensus.fasta'
    output:
        'results/repeatmodeler/{sample}/{sample}-families.fa'
    log:
        'results/logs/repeatmodeler/{sample}.log'
    params:
        out_dir='results/repeatmodeler/{sample}',
        db_name='results/repeatmodeler/{sample}/{sample}'
    threads:
        workflow.cores
    conda:
        'envs/repeatmodeler.yaml'
    shell:
        '''
        BuildDatabase -name {params.db_name} {input} &> {log}
        RepeatModeler -database {params.db_name} -threads {threads} -LTRStruct &>> {log}
        mv RM_* results/logs/repeatmodeler/
        '''

rule repeatmasker:
    input:
        genome= 'results/medaka/{sample}/consensus.fasta',
        library='results/repeatmodeler/{sample}/{sample}-families.fa'
    output:
        'results/repeatmasker/{sample}/consensus.fasta.masked'
    log:
        'results/logs/repeatmasker/{sample}.log'
    params:
        out_dir='results/repeatmasker/{sample}'
    threads:
        workflow.cores
    conda:
        'envs/repeatmodeler.yaml'
    shell:
        '''
        RepeatMasker -lib {input.library} -dir {params.out_dir} -xsmall -pa {threads} {input.genome} &> {log}
        '''

rule braker:
    input:
        'results/repeatmasker/{sample}/consensus.fasta.masked',
    output:
        'results/braker/{sample}/braker.aa',
        'results/braker/{sample}/braker.gtf'
    log:
        'results/logs/braker/{sample}.log'
    params:
        out_dir='results/braker/{sample}',
        config_dir=aug_config,
    threads:
        braker_threads
    container:
        'docker://teambraker/braker3:latest'
    shell:
        '''
        braker.pl \
            --genome {input} \
            --prot_seq resources/Euk_Rhiz_ODB11.fasta \
            --threads {threads} \
            --AUGUSTUS_CONFIG_PATH {params.config_dir} \
            --workingdir {params.out_dir} &> {log}
        '''

rule busco:
    input:
        'results/braker/{sample}/braker.aa'
    output:
        'results/busco/{sample}/short_summary.specific.eukaryota_odb10.{sample}.txt'
    log:
        'results/logs/busco/{sample}.log'
    params:
        out_dir='results/busco/{sample}',
        lineage=os.path.join(busco_downloads, 'lineages/eukaryota_odb10'),
    threads:
        workflow.cores
    container:
        'docker://ezlabgva/busco:v5.8.2_cv1'
    shell:
        '''
        busco \
            -i {input} \
            -o {params.out_dir} \
            -m prot \
            -l {params.lineage} \
            --offline \
            -q \
            -f &> {log}
        rm -r busco_downloads
        '''

rule eggnog:
    input:
        'results/braker/{sample}/braker.aa',
        'results/braker/{sample}/braker.gtf'
    output:
        'results/eggnog/{sample}/eukaryotes.emapper.annotations'
    log:
        'results/logs/eggnog/{sample}.log'
    params:
        out_dir='results/eggnog/{sample}',
        db_dir=os.path.join(str(config['wrapper_dir']), 'resources/eggnog_dbs')
    threads:
        workflow.cores
    conda:
        'envs/eggnog.yaml'
    shell:
        '''
        emapper.py \
            --override \
            -i {input[0]} \
            -o eukaryotes \
            --output_dir {params.out_dir} \
            --cpu {threads} \
            --data_dir {params.db_dir} \
            --tax_scope 2759 \
            --decorate_gff {input[1]} &> {log}
        '''

rule bandage:
    input:
        'results/metaflye/{sample}/assembly_graph.gfa',
        'results/whokaryote/{sample}/whokaryote_predictions_T.tsv',
        'results/whokaryote/{sample}/eukaryotes.fasta'
    output:
        'results/bandage/{sample}/meta_whok.png',
        'results/bandage/{sample}/whokaryote_predictions_T.csv',
        'results/bandage/{sample}/N50.txt'
    log:
        'results/logs/bandage/{sample}.log'
    params:
        out_dir='results/bandage/{sample}',
    threads:
        workflow.cores
    conda:
        'envs/bandage.yaml'
    shell:
        '''
        Bandage info {input[2]} --tsv |cut -f 13 > {params.out_dir}/N50.txt
        cp {input[1]} {params.out_dir}/whokaryote_predictions_T.csv
        sed -i -e 's/contig/edge/g' {params.out_dir}/whokaryote_predictions_T.csv
        sed -i -e 's/predicted/Colour/g' {params.out_dir}/whokaryote_predictions_T.csv
        sed -i -e 's/eukaryote/red/g' {params.out_dir}/whokaryote_predictions_T.csv
        sed -i -e 's/prokaryote/green/g' {params.out_dir}/whokaryote_predictions_T.csv
        sed -i 's/\t/,/g' {params.out_dir}/whokaryote_predictions_T.csv
        Bandage image {input[0]} {params.out_dir}/meta_whok.png --colors {params.out_dir}/whokaryote_predictions_T.csv
        '''

rule cp_final_output:
    input:
        'results/metaflye/{sample}/assembly_graph.gfa',
        'results/whokaryote/{sample}/eukaryotes.fasta',
        'results/braker/{sample}/braker.aa',
        'results/busco/{sample}/short_summary.specific.eukaryota_odb10.{sample}.txt',
        'results/bakta/{sample}/prokaryotes.gff3',

        'results/eggnog/{sample}/eukaryotes.emapper.annotations',
        'results/bandage/{sample}/meta_whok.png',
        'results/nanoplot/{sample}/final_NanoPlot-report.html',
        'results/nanoplot/{sample}/cleaned_NanoPlot-report.html',
        'results/nanoplot/{sample}/eukaryotic_NanoPlot-report.html'
    output:
        'results/final/{sample}/assembly_graph.gfa',
        'results/final/{sample}/eukaryotes.fasta',
        'results/final/{sample}/braker.aa',
        'results/final/{sample}/short_summary.specific.eukaryota_odb10.{sample}.txt',
        'results/final/{sample}/prokaryotes.gff3',

        'results/final/{sample}/eukaryotes.emapper.annotations',
        'results/final/{sample}/meta_whok.png'
        'results/final/{sample}/final_NanoPlot-report.html',
        'results/final/{sample}/cleaned_NanoPlot-report.html',
        'results/final/{sample}/eukaryotic_NanoPlot-report.html'
    log:
        'results/logs/final/{sample}.log'
    threads:
        1
    shell:
        '''
        cp {input[0]} {output[0]} &> {log}
        cp {input[1]} {output[1]} &>> {log}
        cp {input[2]} {output[2]} &>> {log}
        cp {input[3]} {output[3]} &>> {log}
        cp {input[4]} {output[4]} &>> {log}
        cp {input[5]} {output[5]} &>> {log}
        cp {input[6]} {output[6]} &>> {log}
        cp {input[7]} {output[7]} &>> {log}
        cp {input[8]} {output[8]} &>> {log}
        cp {input[9]} {output[9]} &>> {log}

        '''
