import os
q_scores = str(config['qscores']).split(',')
lengths = str(config['lengths']).split(',')
aug_config = os.path.join(str(config['wrapper_dir']), 'resources/augustus_config')
busco_downloads = os.path.join(str(config['wrapper_dir']), 'resources/busco_downloads')
samples = [file.split('.')[0] for file in os.listdir('data') if file.endswith('fastq.gz')]

if workflow.cores > 48:
    braker_threads = 48
else:
    braker_threads = workflow.cores

rule all:
    input:
        expand('results/final/{sample}/eukaryotes.fasta', sample=samples),
        
rule clean_fastq:
    input:
        'data/{sample}.fastq.gz'
    output:
        'results/clean_fastq/{sample}.fastq.gz'
    log:
        'results/logs/clean_fastq/{sample}.log'
    params:
        contam='resources/contaminants.fasta'
    threads:
        workflow.cores
    conda:
        'envs/clean_fastq.yaml'
    shell:
        'minimap2 -t {threads} -ax map-ont {params.contam} {input} 2> {log} | samtools fastq -n -f 4 - 2>> {log} | gzip > {output} 2>> {log}'

rule chopper:
    input:
        'results/clean_fastq/{sample}.fastq.gz'
    output:
        'results/chopper/{sample}.fastq.gz'
    log:
        'results/logs/chopper/{sample}.log'
    params:
        length = 5000,
        quality = 20
    threads:
        workflow.cores
    conda:
        'envs/chopper.yaml'
    shell:
        'gunzip -c {input} 2> {log} | chopper -l {params.length} -q {params.quality} --threads {threads} 2>> {log} | gzip > {output} 2>> {log}'

rule metaflye:
    input:
        'results/chopper/{sample}.fastq.gz'
    output:
        'results/metaflye/{sample}/assembly.fasta',
        'results/metaflye/{sample}/assembly_graph.gfa',
        'results/metaflye/{sample}/assembly_graph.gv',
        'results/metaflye/{sample}/assembly_info.txt',
    log:
        'results/logs/metaflye/{sample}.log'
    params:
        out_dir='results/metaflye/{sample}'
    threads:
        workflow.cores
    conda:
        'envs/flye.yaml'
    shell:
        '''
        flye \
            --meta \
            --nano-hq {input} \
            --out-dir {params.out_dir} \
            --threads {threads} &> {log}
        '''

rule whokaryote:
    input:
        'results/flye/{sample}/assembly.fasta'
    output:
        'results/whokaryote/{sample}/eukaryotes.fasta',
        'results/whokaryote/{sample}/prokaryotes.fasta',
        'results/whokaryote/{sample}/whokaryote_predictions_T.tsv',
    log:
        'results/logs/whokaryote/{sample}.log'
    threads:
        workflow.cores
    params:
        out_dir='results/whokaryote/{sample}',
    conda:
        'envs/whokaryote.yaml'
    shell:
        'whokaryote.py --contigs {input} --outdir {params.out_dir} --threads {threads} --f &> {log}'

rule bakta:
    input:
        'results/whokaryote/{sample}/prokaryotes.fasta'
    output:
        'results/bakta/{sample}/prokaryotes.gff3'
    log:
        'results/logs/bakta/{sample}.log'
    params:
        out_dir='results/bakta/{sample}',
        db=os.path.join(str(config['wrapper_dir']), 'resources/db-light'),
    conda:
        'envs/bakta.yaml'
    shell:
        'bakta --db {params.db} --force --output {params.out_dir} {input} &> {log}'

rule gc_content:
    input:
        'results/whokaryote/{sample}/whokaryote_predictions_T.tsv',
        'results/flye/{sample}/assembly.fasta'
    output:
        'results/gc_content/{sample}/whokaryote_predictions_T_gc.tsv'
    log:
        'results/logs/gc_content/{sample}.log'
    script:
        'scripts/post_who_gc_content.py'

rule cleaner_fastq:
    input:
        'results/whokaryote/{sample}/prokaryotes.fasta',
        'results/clean_fastq/{sample}.fastq.gz'
    output:
        'results/cleaner_fastq/{sample}.fastq.gz'
    log:
        'results/logs/cleaner_fastq/{sample}.log'
    threads:
        workflow.cores
    conda:
        'envs/clean_fastq.yaml'
    shell:
        '''
        minimap2 -t {threads} -ax map-ont {input[0]} {input[1]} 2> {log} | \
        samtools fastq -n -f 4 - | gzip > {output} 2>> {log}
        '''

rule nextdenvovo:
    input:
        'results/cleaner_fastq/{sample}.fastq.gz'
    output:
        'results/nextdenovo/{sample}/assembly.fasta',
        'results/nextdenovo/{sample}/assembly_graph.gfa',
        'results/nextdenovo/{sample}/assembly_graph.gv',
        'results/nextdenovo/{sample}/assembly_info.txt',
    log:
        'results/logs/nextdenovo/{sample}.log'
    params:
        out_dir='results/nextdenovo/{sample}'
    threads:
        workflow.cores
    conda:
        'envs/nextdenovo.yaml'
    shell:
        '''
        nextdenovo \
            --fastq {input} \
            --outdir {params.out_dir} \
            --threads {threads} &> {log}
        '''

rule nextdenovo_whokaryote:
    input:
        'results/nextdenovo/{sample}/assembly.fasta'
    output:
        'results/nextdenovo_whokaryote/{sample}/eukaryotes.fasta',
        'results/nextdenovo_whokaryote/{sample}/prokaryotes.fasta',
        'results/nextdenovo_whokaryote/{sample}/whokaryote_predictions_T.tsv',
    log:
        'results/logs/nextdenovo_whokaryote/{sample}.log'
    threads:
        workflow.cores
    params:
        out_dir='results/nextdenovo_whokaryote/{sample}',
    conda:
        'envs/whokaryote.yaml'
    shell:
        'whokaryote.py --contigs {input} --outdir {params.out_dir} --threads {threads} --f &> {log}'

rule ragtag_scaffold:
    input:
        'results/nextdenovo/{sample}/assembly.fasta',
        'results/nextdenovo/{sample}/assembly_graph.gfa',
        'results/nextdenovo/{sample}/assembly_graph.gv',
        'results/nextdenovo/{sample}/assembly_info.txt'
    output:
        'results/ragtag/{sample}/ragtag.scaffold.fasta',
        'results/ragtag/{sample}/ragtag.scaffold.gff3'
    log:
        'results/logs/ragtag/{sample}.log'
    threads:
        workflow.cores
    params:
        out_dir='results/ragtag/{sample}'
    conda:
        'envs/ragtag.yaml'
    shell:
        '''
        ragtag.py \
            --assembly {input[0]} \
            --gfa {input[1]} \
            --gv {input[2]} \
            --info {input[3]} \
            --outdir {params.out_dir} \
            --threads {threads} &> {log}
        '''

rule quickmerge:
    input:
        'results/nextdenovo/{sample}/assembly.fasta',
        'results/ragtag/{sample}/ragtag.scaffold.fasta'
    output:
        'results/quickmerge/{sample}/merged_assembly.fasta'
    log:
        'results/logs/quickmerge/{sample}.log'
    params:
        out_dir='results/quickmerge/{sample}'
    threads:
        workflow.cores
    conda:
        'envs/quickmerge.yaml'
    shell:
        '''
        quickmerge \
            --input {input[0]} {input[1]} \
            --output {params.out_dir}/merged_assembly.fasta \
            --threads {threads} &> {log}
        '''

rule racon:
    input:
        'results/quickmerge/{sample}/merged_assembly.fasta',
        'results/cleaner_fastq/{sample}.fastq.gz'
    output:
        'results/racon/{sample}/racon_corrected.fasta'
    log:
        'results/logs/racon/{sample}.log'
    params:
        out_dir='results/racon/{sample}'
    threads:
        workflow.cores
    conda:
        'envs/racon.yaml'
    shell:
        '''
        racon \
            -t {threads} \
            {input[1]} \
            {input[0]} \
            {input[1]} > {output} 2> {log}
        '''

rule medaka:
    input:
        'results/racon/{sample}/racon_corrected.fasta',
        'results/cleaner_fastq/{sample}.fastq.gz'
    output:
        'results/medaka/{sample}/medaka_consensus.fasta'
    log:
        'results/logs/medaka/{sample}.log'
    params:
        out_dir='results/medaka/{sample}'
    threads:
        workflow.cores
    conda:
        'envs/medaka.yaml'
    shell:
        '''
        medaka consensus \
            -i {input[1]} \
            -d {input[0]} \
            -o {params.out_dir} \
            -t {threads} &> {log}
        '''

rule repeatmodeler:
    input:
        'results/medaka/{sample}/medaka_consensus.fasta'
    output:
        'results/repeatmodeler/{sample}/{sample}-families.fa'
    log:
        'results/logs/repeatmodeler/{sample}.log'
    params:
        out_dir='results/repeatmodeler/{sample}',
        db_name='results/repeatmodeler/{sample}/{sample}'
    threads:
        workflow.cores
    conda:
        'envs/repeatmodeler.yaml'
    shell:
        '''
        BuildDatabase -name {params.db_name} {input} &> {log}
        RepeatModeler -database {params.db_name} -threads {threads} -LTRStruct &>> {log}
        '''

rule repeatmasker:
    input:
        genome= 'results/medaka/{sample}/medaka_consensus.fasta',
        library='results/repeatmodeler/{sample}/{sample}-families.fa'
    output:
        'results/repeatmasker/{sample}/medaka_consensus.fasta.masked'
    log:
        'results/logs/repeatmasker/{sample}.log'
    params:
        out_dir='results/repeatmasker/{sample}'
    threads:
        workflow.cores
    conda:
        'envs/repeatmodeler.yaml'
    shell:
        '''
        RepeatMasker -lib {input.library} -dir {params.out_dir} -xsmall -pa {threads} {input.genome} &> {log}
        '''

rule braker:
    input:
        'results/repeatmasker/{sample}/medaka_consensus.fasta.masked',
    output:
        'results/braker/{sample}/braker.aa'
    log:
        'results/logs/braker/{sample}.log'
    params:
        out_dir='results/braker/{sample}',
        config_dir=aug_config,
    threads:
        braker_threads
    container:
        'docker://teambraker/braker3:latest'
    shell:
        '''
        braker.pl \
            --genome {input} \
            --esmode \
            --threads {threads} \
            --AUGUSTUS_CONFIG_PATH {params.config_dir} \
            --workingdir {params.out_dir} &> {log}
        '''

rule busco:
    input:
        'results/braker/{sample}/braker.aa'
    output:
        'results/busco/{sample}/short_summary.specific.eukaryota_odb10.{sample}.txt'
    log:
        'results/logs/busco/{sample}.log'
    params:
        out_dir='results/busco/{sample}',
        lineage=os.path.join(busco_downloads, 'lineages/eukaryota_odb10'),
    threads:
        workflow.cores
    container:
        'docker://ezlabgva/busco:v5.8.2_cv1'
    shell:
        '''
        busco \
            -i {input} \
            -o {params.out_dir} \
            -m prot \
            -l {params.lineage} \
            --offline \
            -q \
            -f &> {log}
        rm -r busco_downloads
        '''

rule eggnog:
    input:
        'results/braker/{sample}/braker.aa',
        'results/braker/{sample}/braker.gtf'
    output:
        'results/eggnog/{sample}/eukaryotes.emapper.annotations'
    log:
        'results/logs/eggnog/{sample}.log'
    params:
        out_dir='results/eggnog/{sample}',
        db_dir=os.path.join(str(config['wrapper_dir']), 'resources/eggnog_dbs')
    threads:
        workflow.cores
    conda:
        'envs/eggnog.yaml'
    shell:
        '''
        emapper.py \
            --override \
            -i {input[0]} \
            -o eukaryotes \
            --output_dir {params.out_dir} \
            --cpu {threads} \
            --data_dir {params.db_dir} \
            --tax_scope 2759 \
            --decorate_gff {input[1]} &> {log}
        '''


rule cp_final_output:
    input:
        'results/metaflye/{sample}/assembly_graph.gfa',
        'results/whokaryote/{sample}/eukaryotes.fasta',
        'results/braker/{sample}/braker.aa',
        'results/busco/{sample}/short_summary.specific.eukaryota_odb10.{sample}.txt',
        'results/bakta/{sample}/prokaryotes.gff3',
        'results/gc_content/{sample}/gc_plot.pdf',
        'results/eggnog/{sample}/eukaryotes.emapper.annotations'
    output:
        'results/final/{sample}/assembly_graph.gfa',
        'results/final/{sample}/eukaryotes.fasta',
        'results/final/{sample}/braker.aa',
        'results/final/{sample}/short_summary.specific.eukaryota_odb10.{sample}.txt',
        'results/final/{sample}/prokaryotes.gff3',
        'results/final/{sample}/gc_plot.pdf',
        'results/final/{sample}/eukaryotes.emapper.annotations'
    log:
        'results/logs/final/{sample}.log'
    threads:
        1
    shell:
        '''
        cp {input[0]} {output[0]} &> {log}
        cp {input[1]} {output[1]} &>> {log}
        cp {input[2]} {output[2]} &>> {log}
        cp {input[3]} {output[3]} &>> {log}
        cp {input[4]} {output[4]} &>> {log}
        cp {input[5]} {output[5]} &>> {log}
        cp {input[6]} {output[6]} &>> {log}
        '''
